language: cpp
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
#      - llvm-toolchain-precise-3.7
    packages:
      - build-essential
      - gawk
      - ccache
      - genromfs
      - libc6-i386
      - python-pip
      - python-dev
      - zlib1g-dev
      - gcc-4.9
      - g++-4.9
      - cmake
      - cmake-data
#      - clang-3.7
#      - llvm-3.7

cache:
  ccache: true
  directories:
    - $HOME/opt

before_install:
  - Tools/scripts/configure-ci.sh

script:
  - Tools/scripts/mttr-build-ci.sh

before_cache:
  - ccache -z

compiler:
  - gcc

before_deploy:
  - mkdir $HOME/deploy_files
  - cp ArduCopter/ArduCopter-v2.px4 $HOME/deploy_files
  - cp Tools/autotest/param_metadata/apm.pdef.xml $HOME/deploy_files
  - cp modules/PX4Firmware/Build/px4fmu-v2_APM.build/firmware.elf $HOME/deploy_files/fmu.elf
  - cp modules/PX4Firmware/Build/px4io-v2_default.build/firmware.elf $HOME/deploy_files/io.elf

deploy:
  provider: releases
  api_key: "$GITHUB_DEPLOY_API_KEY"
  file:
    - "$HOME/deploy_files/ArduCopter-v2.px4"
    - "$HOME/deploy_files/fmu.elf"
    - "$HOME/deploy_files/io.elf"
    - "$HOME/deploy_files/apm.pdef.xml"
  on:
    tags: true
