language: cpp
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
#      - llvm-toolchain-precise-3.7
    packages:
      - build-essential
      - gawk
      - ccache
      - genromfs
      - libc6-i386
      - libxml2-dev
      - libxslt1-dev
      - python-pip
      - python-dev
      - zlib1g-dev
      - gcc-4.9
      - g++-4.9
      - cmake
      - cmake-data
#      - clang-3.7
#      - llvm-3.7

cache:
  ccache: true
  directories:
    - $HOME/opt

before_install:
  - Tools/scripts/configure-ci.sh

script:
  - Tools/scripts/mttr-build-ci.sh

before_cache:
  - ccache -z

compiler:
  - gcc

deploy:
  provider: releases
  api_key: "$GITHUB_DEPLOY_API_KEY"
  file_glob: true
  file: "$HOME/deploy_files/*"
  on:
    tags: true
